#=======================================================================================================================
# https://github.com/ophub/op
# Description: Sync Code from ophub/op
# Function: Keep the code in sync with op
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 https://github.com/KFERMercer/OpenWrt-CI
# Copyright (C) 2020 https://github.com/ophub/op
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#=======================================================================================================================

name: Sync Code from ophub/op

on:
  repository_dispatch:
  workflow_dispatch:
  #release:
    #types: published
  #push:
    #branches:
      #- main
    #paths:
      #- '.github/workflows/sync-code.yml'
  #schedule:
    #- cron: '30 23 * * 0'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Load upstream commits
      run: git pull https://github.com/ophub/op.git --log --no-commit

    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
        
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: main
      run: git push origin $DOWNSTREAM_BRANCH
      
      
